### ISSUE TITLE
Getting started docs are wrong

### ISSUE THREAD

**Issue by DavidGOrtega** [somleng/somleng-project#17]
If you follow how to [get started](https://github.com/somleng/somleng-project/blob/master/docs/GETTING_STARTED.md)

You will see that the setup refers to a service ```twilreapi``` that does not exists in the current ```docker-compose.yml``` file. Actually it was removed at https://github.com/somleng/somleng-project/commit/4df97a7e458837eb5163a5f72da0c8435e0c42ff

**Comment by dwilkie** [comment]
Hi, Sorry about this super late reply. We just finished a rewrite of Somleng and have now updated the Getting Started docs.
