### ISSUE TITLE
Problem when changing the dashboard and api domain

### ISSUE THREAD

**Issue by Luskan777** [somleng/somleng-project#40]
Hello,

I'm having trouble running the application in a production environment.

I am not able to change the domain for the application.
I tried changing it using the [documentation](https://www.somleng.org/docs.html#custom_domains_configuration_guide), but it didn't work.

I want to be able to access the application through my domain, not through the address "my-carrier.app.lvh.me:3000"

**Comment by dwilkie** [comment]
Hello @Luskan777 

Thanks for reaching out.

Can you reach out to me at dwilkie@somleng.org and Samnang at samnang@somleng.org and we can help you out.

**Comment by dwilkie** [comment]
@Luskan777 [This PR](https://github.com/somleng/somleng/pull/984) should help with this specific issue. Can you try it? You'll need to use the staging tag from https://gallery.ecr.aws/somleng/somleng to try it out. Then you should be able to set the domain via the `APP_URL_HOST` environment variable

**Comment by Luskan777** [comment]
@dwilkie , yes, I already managed to run the application with the domain through this variable, the environment still runs in development mode, but it works as expected (although it would be better to run in production mode easily)

wouldn't it be interesting to update the documentation for the use of this `APP_URL_HOST` environment variable?
