### ISSUE TITLE
Problem to synthesize voice

### ISSUE THREAD

**Issue by Luskan777** [somleng/somleng-project#41]
Hey guys,

The application is working as expected, however I am having problems selecting a certain language to synthesize speech and to use Polly Voices from Amazon.
The language in which the problem is occurring is pt-BR, in the default language it works normally and I don't use Amazon's Polly Voices.

This is the TwiML instructions:
```
<?xml version="1.0" encoding="UTF-8"?>
  <Response>
    <Say language="pt-BR" voice="Polly.Ricardo" loop="5">Testando Zabbix</Say>
</Response>
```

When querying the freeswitch container logs, it appears this:
<img width="1428" alt="Captura de Tela 2022-12-19 às 21 20 43" src="https://user-images.githubusercontent.com/71342479/208553761-2859fa93-91ee-4f52-abed-262acf993c3d.png">

**Comment by dwilkie** [comment]
You need permissions to call the "polly:SynthesizeSpeech" API on AWS. On our infrastructure we use a Task Role https://github.com/somleng/somleng-switch/blob/7f323c3a7366fce3c0167f47848eff54418c2c65/infrastructure/modules/somleng_switch/switch.tf#L281

But you could also inject your AWS keys with those permissions as environment variables.

here is the code that calls the AWS API:

https://github.com/somleng/somleng-switch/blob/7f323c3a7366fce3c0167f47848eff54418c2c65/components/freeswitch/bin/aws_polly#L11

**Comment by Luskan777** [comment]
Perfect !!

I injected the variables (AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,AWS_DEFAULT_REGION) and it worked correctly, thanks a lot @dwilkie !!

**Comment by Luskan777** [comment]
@dwilkie, another question that has little to do with the current issue.

I noticed that to change a user's password he sends an email using Amazon SES, but I noticed the `mailer_sender` variable in the [app.settings.xml ](https://github.com/somleng/somleng/blob/731dfc53eb89e8901247323d95e5ed1462ef8ce5/config/app_settings.yml)file is static. Would it be possible to customize this value?

**Comment by dwilkie** [comment]
Done. See [this commit](https://github.com/somleng/somleng/commit/c7ccaa77aad2a72fa1afe28904191aaaa4a3a0ef) you can use the `staging` tag https://gallery.ecr.aws/somleng/somleng to test it out.

**Comment by Luskan777** [comment]
I changed the image and added the `MAILER_SENDER` variable to a valid AWS SES account but it didn't work, but I think it didn't work because I'm using the application in development mode (`RAILS_ENV=development`), from what I saw in the [aws_stubs.rb](https://github.com/somleng/somleng/blob/acb2364e57fbfec80bcac749b94058219789b614/config/initializers/aws_stubs.rb) file, it prevents the use of AWS credentials in development environment.
I cannot use the production environment the application requires a lot of AWS resources. but thank you very much for the reply and for the change.

**Comment by dwilkie** [comment]
Yes. We recommend that you run the application in production mode in  production environments. If there are any dependencies on external services we should have them configurable via environment variables. Let us know which parts are hardcoded in production that you need configurable and we can work on making them configurable.
